
name: Notify

on:
  push:
    tags:
      - 'v*'

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: notify-teams-module-channel
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.MODULE_DEV_TEAMS_WEBHOOK }}
        title: MODI+ ${{ github.ref_name }} is released!!
        summary: MODI+ ${{ github.ref_name }} is released!!
        text: |
          MODI+ 모듈 펌웨어 ${{ github.ref_name }} 버전이 릴리즈 되었습니다.

          MODI+ Firmware Updater 실행 시, 자동으로 업데이트하여 이용하실 수 있습니다.

          펌웨어 변경 사항은 릴리즈 노트를 참고해 주시기 바랍니다.

          URL: https://github.com/LUXROBO/modi2-module-release/releases/tag/${{ github.ref_name }}

          버전정보: https://download.luxrobo.com/modi2-module-firmware/version.json

          릴리즈 노트: https://download.luxrobo.com/modi2-module-firmware/release_notes.md

          모듈 펌웨어: https://download.luxrobo.com/modi2-module-firmware/firmware.zip
